// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh07USiOlXXHtHLbTkARY3di_lEOjRpMs',
    appId: '1:466245152970:web:4a02be181c68f881fb0433',
    messagingSenderId: '466245152970',
    projectId: 'rayek-001',
    authDomain: 'rayek-001.firebaseapp.com',
    storageBucket: 'rayek-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfBQmlKAMdIk3tT6QW9bb16G31My0QUGA',
    appId: '1:466245152970:android:96021a382686415dfb0433',
    messagingSenderId: '466245152970',
    projectId: 'rayek-001',
    storageBucket: 'rayek-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvF_vZ0EuPlY8tAOJWp1v2iMWX-vOI_gA',
    appId: '1:466245152970:ios:13241001aed3c970fb0433',
    messagingSenderId: '466245152970',
    projectId: 'rayek-001',
    storageBucket: 'rayek-001.appspot.com',
    iosClientId:
        '466245152970-9q6c3jbsfo8d193b8krodrduaeeump6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.rayekV001',
  );
}
